<?php
/**
 * Created by PhpStorm.
 * User: zunly
 * Date: 2018/11/25
 * Time: 16:01
 */

namespace app\index\model;


use think\Model;

class AdminLog extends Model
{
    protected $table = 'ty_admin_log';

    // 开启自动写入时间戳
    protected $autoWriteTimestamp = true;

    public function admin()
    {
        // 用户HAS ONE档案关联
        return $this->belongsTo('Admin');
        //return $this->hasOne('Admin');
    }

    public static function getAllAdminLogWithAdminName($page)
    {
        $pageConfig = ['page' => $page];
        return self::with('Admin')->order('log_time', 'desc')->paginate($pageConfig);//->select();
    }

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->table = 'ty_admin_log';

        //查询数据表字段信息
        $this->field = $this->db()->getTableInfo('', 'fields');

        //查询数据表字段类型
        $this->type = $this->db()->getTableInfo('', 'type');

        //查询数据表主键
        $this->pk = $this->db()->getTableInfo('', 'pk');

    }

}